config/routes.rb
FightBets::Application.routes.draw do
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  resources :users

  resources :user_sessions
  match 'login'  => 'user_sessions#new',     :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :fights
  resources :events
  resources :bets
  resources :password_resets
  root :to => 'fights#index'

end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  validates_confirmation_of :password, :message => "password e confirmação deve ser identicos", :if => :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_presence_of :username
  validates_uniqueness_of :email

  has_many :bets
  ROLES = %w[admin player banned]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :except => [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @future_bets = @user.bets.select{|b| b.fight.result == nil}
    @past_bets   = @user.bets.select{|b| b.fight.result != nil}

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.role = 'player' #por enquanto por seguranca todos serao players

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario cadastrado com sucesso.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario atualizado!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def current_user
    @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def bet_won(fight_bet,fight)
    if fight.result
      if fight_bet.winner == fight.result.winner
        "Ganhou"
      else
        "Perdeu"
      end
    else
      false
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password%><br />
    <%= f.text_field :password%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation%><br />
    <%= f.text_field :password_confirmation%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Proximas Apostas:</b> <br/>
  
<table>
  <tr>
    <th>Categoria</th>
    <th>Red Corner</th>
    <th>   </th>
    <th>Blue Corner</th>
    <th><b>Aposta</b></th>
  </tr>
  <% @future_bets.each do |fb| %>
  <tr>
    <td><%= fb.fight.category  %> </td>
    <td><%= fb.fight.contender %> </td>
    <td> VS </td>
    <td><%= fb.fight.challenger%> </td>
    <td><b><%= fb.winner%> </b></td>
  </tr>
  <% end %>
</table>
</p>
<p>
  <b>Ultimas Apostas:</b> <br/>
  
<table>
  <tr>
    <th>Categoria</th>
    <th>Red Corner</th>
    <th>   </th>
    <th>Blue Corner</th>
    <th>Aposta?</th>
  </tr>
  <% @past_bets.each do |pb| %>
  <tr>
    <td><%= pb.fight.category  %> </td>
    <td><%= pb.fight.contender %> </td>
    <td> VS </td>
    <td><%= pb.fight.challenger%> </td>
    <td><%= bet_won(pb, pb.fight)%> </td>
  </tr>
  <% end %>
</table>
</p>

<%= link_to 'Editar Usuario', edit_user_path(@user) %> |
<%= link_to 'Apostar', events_path %>