config/routes.rb
FightBets::Application.routes.draw do
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  resources :users

  resources :user_sessions
  match 'login'  => 'user_sessions#new',     :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :fights
  resources :events
  resources :bets
  resources :password_resets
  root :to => 'fights#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :when

  has_many :fights
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource

  before_filter :require_login, :except => [:show]
  def index
    @events = Event.includes(:fights, {:fights => :bets}, :fights => :result).all
    if logged_in?
      @bet = Bet.new
      @bet.user_id = current_user.id
      @current_user_bets = current_user.bets.includes(:fight)
    end 
  end

  def show
    @event = Event.includes(:fights).find(params[:id])
    @fight = Fight.new
    @fight.event_id = @event.id
  end

  def new
    @event = Event.new
  end

  def create
    #raise params.inspect
    @event = Event.new
    @event.title = params[:event][:title]
    @event.when = Date.parse("#{params[:start_date][:day]} #{params[:start_date][:month]} #{params[:start_date][:year]}")
    @event.save
    redirect_to event_path(@event)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def non_betted_fights(event, current_user_id)
    list = []
    event.fights.each do |fight|
      list <<  fight unless fight.bets.exists?(:user_id => current_user_id)
    end
    list
   end 

  def avaliable_fights(fights, current_user_bets)
    list = []
    current_user_bets.each do |bet|
      list << bet.fight
    end  
    fights - list
  end

end

app/views/events/_event.html.erb
<div class="event">
    <li>
    <%= link_to event.title, event_path(event) if avaliable_fights(event.fights, @current_user_bets).size > 0 %>

      <table>
      <%= form_tag(:controller => "bets", :action => "create") do -%>
          
        <%= hidden_field_tag(:user_id, @bet.user_id) %>
          <% avaliable_fights(event.fights, @current_user_bets).each do |fight| %>
          <tr>
            <td><%= fight.category  %> </td>
            <td><%= radio_button_tag(fight.id.to_s.to_sym, fight.contender) %><%= fight.contender %> </td>
            <td> VS </td>
            <td><%= radio_button_tag(fight.id.to_s.to_sym, fight.challenger) %><%= fight.challenger%> </td>
          </tr>
          <% end %>
          <tr>
            <td><%= submit_tag 'Apostar' if avaliable_fights(event.fights, @current_user_bets).size > 0 %> </td>
          </tr>
        <% end -%>
      </table>
    </li>
</div>

app/views/events/_event_form.html.erb
<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :title%>
    <%= f.text_field :title %> 
  </p>
  <p>
    <%= select_date Date.today, :prefix => :start_date %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/_fight_form.html.erb
<%
  categorias_array = [['mosca','Mosca'],['galo','Galo'],['pena', 'Pena'],['leve', 'Leve'],['meio médio', 'Meio Médio'],['médio','Médio'],['meio pesado','Meio Pesado'], ['pesado','Pesado']]
%>
<h3>Cadastrar nova luta</h3>

<%= form_for(@fight) do |f| %>
  <%= f.hidden_field :event_id %>
  <p>
  <%= f.label :categoria%>
  <%= f.select(:category, categorias_array ) %> 
  </p>
  <p>
    <%= f.label :red_corner %>
    <%= f.text_field :contender %>
  </p>
  <p>
    <%= f.label :blue_corner %>
    <%= f.text_field :challenger %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/index.html.erb
<h1>todos eventos</h1>

<ul>
  <li>

    <table>
      <tr>
        <th>Categoria</th>
        <th>Red Corner</th>
        <th>   </th>
        <th>Blue Corner</th>
      </tr>
    </table>
    <%= render :partial => "event", :collection => @events %>
  </li>
</ul>
<% if can? :update, @events %>
  <%= link_to "cadastrar evento", new_event_path %>
<% end %>

app/views/events/new.html.erb
<h1>Novo Evento</h1>

<%= render :partial => "event_form" %>

app/views/events/show.html.erb
<h1><%= @event.title %> 
    <%= @event.when.to_s%>
</h1>
<h3>Lutas Previstas</h3>

<table>
  <tr>
    <th>Categoria</th>
    <th>Red Corner</th>
    <th>   </th>
    <th>Blue Corner</th>
  </tr>
  <% @event.fights.each do |fight| %>
  <tr>
    <td><%= fight.category  %> </td>
    <td><%= fight.contender %> </td>
    <td> VS </td>
    <td><%= fight.challenger%> </td>
    <td>
   
      <% if can? :destroy, fight %>
      <%= link_to 'Remover Luta', fight,
                    :confirm => 'Apagar Luta, tem certeza?',
                    :method => :delete %> 
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

<% if can? :update, @event %>
  <%= render :partial => "fight_form" %>
<% end %>