config/routes.rb
FightBets::Application.routes.draw do
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  resources :users

  resources :user_sessions
  match 'login'  => 'user_sessions#new',     :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :fights
  resources :events
  resources :bets
  resources :password_resets
  root :to => 'fights#index'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:username], params[:password])
      redirect_back_or_to(user_path(@user), :message => 'Voce esta logado.')
    else  
      flash.now[:alert] = "Login failed."
      render :action => :new
    end
  end

  def destroy
    logout
    redirect_to(:root, :message => 'Deslogado com sucesso!')
  end
end

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
  <%= form_tag(user_sessions_path, :method => :post) do %>

  <p>
    username<br />
    <%= text_field_tag "username" %>
  </p>
  <p>
    password<br />
    <%= password_field_tag "password"%>
  </p>
  <p>
    <%= submit_tag 'Submit' %>
  </p>
  <% end %>  

  <%= link_to 'Voltar', users_path %>
  
  <h1>Esqueceu a Senha?</h1>
  <%= render 'forgot_password_form' %>